version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./SimpleWebApiTests/SimpleWebApiTests.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./SimpleWebApiTests/SimpleWebApiTests.csproj
clone_depth: 1
deploy: off